package view;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

import model.*;
import controller.*;
	

public class CustomizeCakeView extends javax.swing.JFrame {
    /**
     * Creates new form CustomizeCakeView
     */
    public RegistrationModel rModel;
    CustomizeCakeModel cModel= new CustomizeCakeModel();
    
    public CustomizeCakeView(RegistrationModel rModel) {
        initComponents();
        this.rModel=rModel;
        okButton.setEnabled(false);
        new CustomizeCakeController(this);
    }
    
    public void addCustomizeCakeListener(ActionListener listenForEvents){
	    sixInchButton.addActionListener(listenForEvents);
	    eightInchButton.addActionListener(listenForEvents);
	    tenInchButton.addActionListener(listenForEvents);
	    twelveInchButton.addActionListener(listenForEvents);
	    
	    oneLayerButton.addActionListener(listenForEvents);
	    twoLayerButton.addActionListener(listenForEvents);
	    threeLayerButton.addActionListener(listenForEvents);
	    
	    eggCakeButton.addActionListener(listenForEvents);
	    egglessCakeButton.addActionListener(listenForEvents);
	    
	    redColorButton.addActionListener(listenForEvents);
	    greenColorButton.addActionListener(listenForEvents);
	    cyanColorButton.addActionListener(listenForEvents);
	    yellowColorButton.addActionListener(listenForEvents);
	    blueColorButton.addActionListener(listenForEvents);
	    pinkColorButton.addActionListener(listenForEvents);
	    whiteColorButton.addActionListener(listenForEvents);
	    orangeColorButton.addActionListener(listenForEvents);
	    purpleColorButton.addActionListener(listenForEvents);
	    
	    
	    strawberryFillingButton.addActionListener(listenForEvents);
	    vanillaFillingButton.addActionListener(listenForEvents);
	    chocolateFillingButton.addActionListener(listenForEvents);
	    
	    okButton.addActionListener(listenForEvents);
	    
	    printButton.addActionListener(listenForEvents);
	    proceedButton.addActionListener(listenForEvents);
	    
        backButton.addActionListener(listenForEvents);
    }
    
    public String getColourButton(ActionEvent action) throws Exception{
	    var buttonClass = action.getSource();

	    if (buttonClass==redColorButton){
		    return "redColorButton";
	    }else if (buttonClass==greenColorButton){
		    return "greenColorButton";
	    }else if (buttonClass==cyanColorButton){
		    return "cyanColorButton";
	    }else if (buttonClass==yellowColorButton){
		    return "yellowColorButton";
	    }else if (buttonClass==blueColorButton){
		    return "blueColorButton";
	    }else if (buttonClass==pinkColorButton){
		    return "pinkColorButton";
	    }else if (buttonClass==whiteColorButton){
		    return "whiteColorButton";
	    }else if (buttonClass==orangeColorButton){
		    return "orangeColorButton";
	    }else if (buttonClass==purpleColorButton){
		    return "purpleColorButton";
	    }else if (buttonClass==backButton){
            return "BACK";
        }
	    else{
		    throw new Exception("Unknown Button ");
	    }
    }

    public String getMessageBoxText(){
        return messageTextField.getText();
    }
    
    public void openDashboard(){
//        DashboardView DaB = new DashboardView(rModel);
//        DaB.setVisible(true);
//        dispose();
    }
    
    public void openCart(CartModel cartMod){
//        CartView cV = new CartView(cartMod);
//                   
//        cV.setVisible(true);
//        dispose();
    }
    
    public void enableOkButton(boolean enable){
        okButton.setEnabled(enable);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        eightInchButton = new javax.swing.JButton();
        tenInchButton = new javax.swing.JButton();
        twelveInchButton = new javax.swing.JButton();
        sixInchButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        oneLayerButton = new javax.swing.JButton();
        threeLayerButton = new javax.swing.JButton();
        twoLayerButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        eggCakeButton = new javax.swing.JButton();
        egglessCakeButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        greenColorButton = new javax.swing.JButton();
        redColorButton = new javax.swing.JButton();
        purpleColorButton = new javax.swing.JButton();
        orangeColorButton = new javax.swing.JButton();
        blueColorButton = new javax.swing.JButton();
        yellowColorButton = new javax.swing.JButton();
        whiteColorButton = new javax.swing.JButton();
        cyanColorButton = new javax.swing.JButton();
        pinkColorButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        messageTextField = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        strawberryFillingButton = new javax.swing.JButton();
        vanillaFillingButton = new javax.swing.JButton();
        chocolateFillingButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        SizeField = new javax.swing.JTextField();
        cakeTypeField = new javax.swing.JTextField();
        icingColorField = new javax.swing.JTextField();
        messageField = new javax.swing.JTextField();
        layersField = new javax.swing.JTextField();
        fillingField = new javax.swing.JTextField();
        btnHome1 = new javax.swing.JButton();
        proceedButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(252, 230, 209));
        setMinimumSize(new java.awt.Dimension(1200, 660));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(252, 230, 209));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(249, 172, 117));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Choose Size:");

        eightInchButton.setBackground(new java.awt.Color(171, 213, 255));
        eightInchButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        eightInchButton.setForeground(new java.awt.Color(0, 0, 0));
        eightInchButton.setText("8\"");
        eightInchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightInchButtonActionPerformed(evt);
            }
        });

        tenInchButton.setBackground(new java.awt.Color(171, 213, 255));
        tenInchButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        tenInchButton.setForeground(new java.awt.Color(0, 0, 0));
        tenInchButton.setText("10\"");
        tenInchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenInchButtonActionPerformed(evt);
            }
        });

        twelveInchButton.setBackground(new java.awt.Color(171, 213, 255));
        twelveInchButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        twelveInchButton.setForeground(new java.awt.Color(0, 0, 0));
        twelveInchButton.setText("12\"");
        twelveInchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twelveInchButtonActionPerformed(evt);
            }
        });

        sixInchButton.setBackground(new java.awt.Color(171, 213, 255));
        sixInchButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        sixInchButton.setForeground(new java.awt.Color(0, 0, 0));
        sixInchButton.setText("6\"");
        sixInchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixInchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sixInchButton)
                    .addComponent(tenInchButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(twelveInchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eightInchButton))
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eightInchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sixInchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenInchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twelveInchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(249, 172, 117));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Number of layers:");

        oneLayerButton.setBackground(new java.awt.Color(171, 213, 255));
        oneLayerButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        oneLayerButton.setForeground(new java.awt.Color(0, 0, 0));
        oneLayerButton.setText("1");
        oneLayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneLayerButtonActionPerformed(evt);
            }
        });

        threeLayerButton.setBackground(new java.awt.Color(171, 213, 255));
        threeLayerButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        threeLayerButton.setForeground(new java.awt.Color(0, 0, 0));
        threeLayerButton.setText("3");
        threeLayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeLayerButtonActionPerformed(evt);
            }
        });

        twoLayerButton.setBackground(new java.awt.Color(171, 213, 255));
        twoLayerButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        twoLayerButton.setForeground(new java.awt.Color(0, 0, 0));
        twoLayerButton.setText("2");
        twoLayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoLayerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(oneLayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(twoLayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(threeLayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oneLayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twoLayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(threeLayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(249, 172, 117));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Choose Type:");

        eggCakeButton.setBackground(new java.awt.Color(171, 213, 255));
        eggCakeButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        eggCakeButton.setForeground(new java.awt.Color(0, 0, 0));
        eggCakeButton.setText("Egg Cake");
        eggCakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eggCakeButtonActionPerformed(evt);
            }
        });

        egglessCakeButton.setBackground(new java.awt.Color(171, 213, 255));
        egglessCakeButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        egglessCakeButton.setForeground(new java.awt.Color(0, 0, 0));
        egglessCakeButton.setText("Eggless Cake");
        egglessCakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                egglessCakeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eggCakeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(egglessCakeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addGap(24, 24, 24)
                .addComponent(eggCakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(egglessCakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(249, 172, 117));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel5.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Choose icing colour:");

        greenColorButton.setBackground(new java.awt.Color(0, 173, 48));
        greenColorButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        greenColorButton.setForeground(new java.awt.Color(0, 0, 0));
        greenColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenColorButtonActionPerformed(evt);
            }
        });

        redColorButton.setBackground(new java.awt.Color(255, 46, 46));
        redColorButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        redColorButton.setForeground(new java.awt.Color(0, 0, 0));
        redColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redColorButtonActionPerformed(evt);
            }
        });

        purpleColorButton.setBackground(new java.awt.Color(168, 128, 255));
        purpleColorButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        purpleColorButton.setForeground(new java.awt.Color(0, 0, 0));
        purpleColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purpleColorButtonActionPerformed(evt);
            }
        });

        orangeColorButton.setBackground(new java.awt.Color(255, 149, 149));
        orangeColorButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        orangeColorButton.setForeground(new java.awt.Color(0, 0, 0));
        orangeColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orangeColorButtonActionPerformed(evt);
            }
        });

        blueColorButton.setBackground(new java.awt.Color(3, 59, 255));
        blueColorButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        blueColorButton.setForeground(new java.awt.Color(0, 0, 0));
        blueColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueColorButtonActionPerformed(evt);
            }
        });

        yellowColorButton.setBackground(new java.awt.Color(255, 240, 107));
        yellowColorButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        yellowColorButton.setForeground(new java.awt.Color(0, 0, 0));
        yellowColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yellowColorButtonActionPerformed(evt);
            }
        });

        whiteColorButton.setBackground(new java.awt.Color(217, 217, 217));
        whiteColorButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        whiteColorButton.setForeground(new java.awt.Color(0, 0, 0));
        whiteColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiteColorButtonActionPerformed(evt);
            }
        });

        cyanColorButton.setBackground(new java.awt.Color(102, 200, 255));
        cyanColorButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        cyanColorButton.setForeground(new java.awt.Color(0, 0, 0));
        cyanColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cyanColorButtonActionPerformed(evt);
            }
        });

        pinkColorButton.setBackground(new java.awt.Color(253, 156, 255));
        pinkColorButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        pinkColorButton.setForeground(new java.awt.Color(0, 0, 0));
        pinkColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinkColorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(yellowColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cyanColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pinkColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(orangeColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blueColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(whiteColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(redColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(greenColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(purpleColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addGap(8, 8, 8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(greenColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purpleColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blueColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orangeColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(whiteColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cyanColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yellowColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pinkColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(249, 172, 117));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Message:");

        messageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageTextFieldActionPerformed(evt);
            }
        });

        okButton.setBackground(new java.awt.Color(204, 204, 255));
        okButton.setForeground(new java.awt.Color(0, 0, 0));
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(okButton)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(messageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(okButton)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(249, 172, 117));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Choose Filling:");

        strawberryFillingButton.setBackground(new java.awt.Color(171, 213, 255));
        strawberryFillingButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        strawberryFillingButton.setForeground(new java.awt.Color(0, 0, 0));
        strawberryFillingButton.setText("Strawberry");
        strawberryFillingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strawberryFillingButtonActionPerformed(evt);
            }
        });

        vanillaFillingButton.setBackground(new java.awt.Color(171, 213, 255));
        vanillaFillingButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        vanillaFillingButton.setForeground(new java.awt.Color(0, 0, 0));
        vanillaFillingButton.setText("Vanilla");
        vanillaFillingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vanillaFillingButtonActionPerformed(evt);
            }
        });

        chocolateFillingButton.setBackground(new java.awt.Color(171, 213, 255));
        chocolateFillingButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        chocolateFillingButton.setForeground(new java.awt.Color(0, 0, 0));
        chocolateFillingButton.setText("Chocolate");
        chocolateFillingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chocolateFillingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chocolateFillingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(strawberryFillingButton, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(vanillaFillingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(strawberryFillingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(vanillaFillingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chocolateFillingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        printButton.setBackground(new java.awt.Color(255, 153, 102));
        printButton.setFont(new java.awt.Font("The Bold Font", 0, 18)); // NOI18N
        printButton.setForeground(new java.awt.Color(0, 0, 0));
        printButton.setText("PRINT");
        printButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(249, 172, 117));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel7.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Size:");

        jLabel8.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Layers:");

        jLabel9.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Cake Type:");

        jLabel10.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Icing Colour:");

        jLabel11.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Filling");

        jLabel12.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Message:");

        SizeField.setEditable(false);
        SizeField.setBackground(new java.awt.Color(255, 255, 255));
        SizeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SizeFieldActionPerformed(evt);
            }
        });

        cakeTypeField.setEditable(false);
        cakeTypeField.setBackground(new java.awt.Color(255, 255, 255));
        cakeTypeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cakeTypeFieldActionPerformed(evt);
            }
        });

        icingColorField.setEditable(false);
        icingColorField.setBackground(new java.awt.Color(255, 255, 255));
        icingColorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icingColorFieldActionPerformed(evt);
            }
        });

        messageField.setEditable(false);
        messageField.setBackground(new java.awt.Color(255, 255, 255));
        messageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageFieldActionPerformed(evt);
            }
        });

        layersField.setEditable(false);
        layersField.setBackground(new java.awt.Color(255, 255, 255));
        layersField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layersFieldActionPerformed(evt);
            }
        });

        fillingField.setEditable(false);
        fillingField.setBackground(new java.awt.Color(255, 255, 255));
        fillingField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillingFieldActionPerformed(evt);
            }
        });

        btnHome1.setBackground(new java.awt.Color(255, 204, 204));
        btnHome1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        btnHome1.setForeground(new java.awt.Color(0, 0, 0));
        btnHome1.setText("FINAL PRODUCT");
        btnHome1.setBorder(null);
        btnHome1.setBorderPainted(false);
        btnHome1.setContentAreaFilled(false);
        btnHome1.setDefaultCapable(false);
        btnHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SizeField)
                                    .addComponent(layersField)
                                    .addComponent(cakeTypeField)
                                    .addComponent(icingColorField)
                                    .addComponent(fillingField)
                                    .addComponent(messageField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btnHome1)
                        .addGap(100, 100, 100))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(btnHome1)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(SizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(layersField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cakeTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(icingColorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(fillingField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(messageField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        proceedButton.setBackground(new java.awt.Color(255, 153, 102));
        proceedButton.setFont(new java.awt.Font("The Bold Font", 0, 18)); // NOI18N
        proceedButton.setForeground(new java.awt.Color(0, 0, 0));
        proceedButton.setText("PROCEED");
        proceedButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        proceedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(204, 204, 255));
        backButton.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(0, 0, 0));
        backButton.setText("← BACK");
        backButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(proceedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 30, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(proceedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74))))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1200, 660);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void fillCustomizeCakeData(CustomizeCakeModel cModel){
	SizeField.setText(cModel.getSize()+"\"");
	layersField.setText(Integer.toString(cModel.getLayers()));
	cakeTypeField.setText(cModel.getType());
	icingColorField.setText(cModel.getColor());
	fillingField.setText(cModel.getFilling());
	messageField.setText(cModel.getMessage());
    
    }
        
    public void disableAllSizeButtons(){
	    /*
	    * disables all choose size buttons
	    */
	    sixInchButton.setEnabled(false);
	    eightInchButton.setEnabled(false);
	    tenInchButton.setEnabled(false);
	    twelveInchButton.setEnabled(false);
    }
    
    public void disabeleAllNumberOfLayersButtons(){
	    oneLayerButton.setEnabled(false);
	    twoLayerButton.setEnabled(false);
	    threeLayerButton.setEnabled(false);
    }
    
    public void disableAllChooseTypeButtons(){
	    eggCakeButton.setEnabled(false);
	    egglessCakeButton.setEnabled(false);
            
    }
    
    public void disableAllIcingColorButtons(){
	    redColorButton.setEnabled(false);
	    greenColorButton.setEnabled(false);
	    purpleColorButton.setEnabled(false);
	    orangeColorButton.setEnabled(false);
	    blueColorButton.setEnabled(false);
	    whiteColorButton.setEnabled(false);
	    yellowColorButton.setEnabled(false);
	    cyanColorButton.setEnabled(false);
	    pinkColorButton.setEnabled(false);
    }
    
    public void disableAllFillingButtons(){
	    strawberryFillingButton.setEnabled(false);
	    vanillaFillingButton.setEnabled(false);
	    chocolateFillingButton.setEnabled(false);
    }
    
    
    
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
	cModel.setType("Butter");
	disableAllChooseTypeButtons();
    }                                                

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
	
    }                                                      

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void btnHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome1ActionPerformed

    private void fillingFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillingFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fillingFieldActionPerformed

    private void layersFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_layersFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_layersFieldActionPerformed

    private void messageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageFieldActionPerformed

    private void icingColorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icingColorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_icingColorFieldActionPerformed

    private void cakeTypeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cakeTypeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cakeTypeFieldActionPerformed

    private void SizeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SizeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SizeFieldActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        // TODO add your handling code here:
;
    }//GEN-LAST:event_printButtonActionPerformed

    private void chocolateFillingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chocolateFillingButtonActionPerformed
	
    }//GEN-LAST:event_chocolateFillingButtonActionPerformed

    private void vanillaFillingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vanillaFillingButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_vanillaFillingButtonActionPerformed

    private void strawberryFillingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strawberryFillingButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_strawberryFillingButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    }//GEN-LAST:event_okButtonActionPerformed

    private void messageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageTextFieldActionPerformed

    private void pinkColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinkColorButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pinkColorButtonActionPerformed

    private void cyanColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cyanColorButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cyanColorButtonActionPerformed

    private void whiteColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiteColorButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_whiteColorButtonActionPerformed

    private void yellowColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yellowColorButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_yellowColorButtonActionPerformed

    private void blueColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueColorButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_blueColorButtonActionPerformed

    private void orangeColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orangeColorButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_orangeColorButtonActionPerformed

    private void purpleColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purpleColorButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_purpleColorButtonActionPerformed

    private void redColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redColorButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_redColorButtonActionPerformed

    private void greenColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenColorButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_greenColorButtonActionPerformed

    private void egglessCakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_egglessCakeButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_egglessCakeButtonActionPerformed

    private void eggCakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eggCakeButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_eggCakeButtonActionPerformed

    private void twoLayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoLayerButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_twoLayerButtonActionPerformed

    private void threeLayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeLayerButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_threeLayerButtonActionPerformed

    private void oneLayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneLayerButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_oneLayerButtonActionPerformed

    private void sixInchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixInchButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_sixInchButtonActionPerformed

    private void twelveInchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twelveInchButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_twelveInchButtonActionPerformed

    private void tenInchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenInchButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tenInchButtonActionPerformed

    private void eightInchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightInchButtonActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_eightInchButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_backButtonActionPerformed

        private void proceedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedButtonActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_proceedButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomizeCakeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomizeCakeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomizeCakeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomizeCakeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
		RegistrationModel model= new RegistrationModel();
                new CustomizeCakeView(model).setVisible(true);
		
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SizeField;
    private javax.swing.JButton backButton;
    private javax.swing.JButton blueColorButton;
    private javax.swing.JButton btnHome1;
    private javax.swing.JTextField cakeTypeField;
    private javax.swing.JButton chocolateFillingButton;
    private javax.swing.JButton cyanColorButton;
    private javax.swing.JButton eggCakeButton;
    private javax.swing.JButton egglessCakeButton;
    private javax.swing.JButton eightInchButton;
    private javax.swing.JTextField fillingField;
    private javax.swing.JButton greenColorButton;
    private javax.swing.JTextField icingColorField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField layersField;
    private javax.swing.JTextField messageField;
    private javax.swing.JTextField messageTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JButton oneLayerButton;
    private javax.swing.JButton orangeColorButton;
    private javax.swing.JButton pinkColorButton;
    private javax.swing.JButton printButton;
    private javax.swing.JButton proceedButton;
    private javax.swing.JButton purpleColorButton;
    private javax.swing.JButton redColorButton;
    private javax.swing.JButton sixInchButton;
    private javax.swing.JButton strawberryFillingButton;
    private javax.swing.JButton tenInchButton;
    private javax.swing.JButton threeLayerButton;
    private javax.swing.JButton twelveInchButton;
    private javax.swing.JButton twoLayerButton;
    private javax.swing.JButton vanillaFillingButton;
    private javax.swing.JButton whiteColorButton;
    private javax.swing.JButton yellowColorButton;
    // End of variables declaration//GEN-END:variables
}
