package view;


import model.*;


public class CustomizeCakeView extends javax.swing.JFrame {
    /**
     * Creates new form CustomizeCakeView
     */
    RegistrationModel rModel;

    public CustomizeCakeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jTextField6 = new javax.swing.JTextField();
                jPanel1 = new javax.swing.JPanel();
                jSeparator1 = new javax.swing.JSeparator();
                jPanel2 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                eightInchButton = new javax.swing.JButton();
                tenInchButton = new javax.swing.JButton();
                twelveInchButton = new javax.swing.JButton();
                sixInchButton = new javax.swing.JButton();
                jPanel3 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                oneLayerButton = new javax.swing.JButton();
                threeLayerButton = new javax.swing.JButton();
                twoLayerButton = new javax.swing.JButton();
                jPanel4 = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                poundCakeButton = new javax.swing.JButton();
                spongeCakeButton = new javax.swing.JButton();
                butterCakeButton = new javax.swing.JButton();
                jPanel6 = new javax.swing.JPanel();
                jLabel5 = new javax.swing.JLabel();
                greenColorButton = new javax.swing.JButton();
                redColorButton = new javax.swing.JButton();
                purpleColorButton = new javax.swing.JButton();
                orangeColorButton = new javax.swing.JButton();
                blueColorButton = new javax.swing.JButton();
                yellowColorButton = new javax.swing.JButton();
                whiteColorButton = new javax.swing.JButton();
                cyanColorButton = new javax.swing.JButton();
                pinkColorButton = new javax.swing.JButton();
                jPanel7 = new javax.swing.JPanel();
                jLabel6 = new javax.swing.JLabel();
                messageTextField = new javax.swing.JTextField();
                okButton = new javax.swing.JButton();
                jPanel8 = new javax.swing.JPanel();
                jLabel4 = new javax.swing.JLabel();
                chocolateFillingButton = new javax.swing.JButton();
                strawberryFillingButton = new javax.swing.JButton();
                vanillaFillingButton = new javax.swing.JButton();
                proceedButton = new javax.swing.JButton();
                btnProfile = new javax.swing.JButton();
                btnCart = new javax.swing.JButton();
                btnHome = new javax.swing.JButton();
                btnItems = new javax.swing.JButton();
                btnContactUs = new javax.swing.JButton();
                btnAboutUs = new javax.swing.JButton();
                jPanel5 = new javax.swing.JPanel();
                jLabel7 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                jLabel9 = new javax.swing.JLabel();
                jLabel10 = new javax.swing.JLabel();
                jLabel11 = new javax.swing.JLabel();
                jLabel12 = new javax.swing.JLabel();
                SizeField = new javax.swing.JTextField();
                cakeTypeField = new javax.swing.JTextField();
                icingColorField = new javax.swing.JTextField();
                messageField = new javax.swing.JTextField();
                layersField = new javax.swing.JTextField();
                fillingField = new javax.swing.JTextField();
                btnHome1 = new javax.swing.JButton();

                jTextField6.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextField6ActionPerformed(evt);
                        }
                });

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setAutoRequestFocus(false);
                setBackground(new java.awt.Color(252, 230, 209));
                setMinimumSize(new java.awt.Dimension(1200, 660));
                getContentPane().setLayout(null);

                jPanel1.setBackground(new java.awt.Color(252, 230, 209));

                jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
                jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

                jPanel2.setBackground(new java.awt.Color(249, 172, 117));
                jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

                jLabel1.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
                jLabel1.setText("Choose Size:");

                eightInchButton.setBackground(new java.awt.Color(171, 213, 255));
                eightInchButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
                eightInchButton.setText("8\"");
                eightInchButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                eightInchButtonActionPerformed(evt);
                        }
                });

                tenInchButton.setBackground(new java.awt.Color(171, 213, 255));
                tenInchButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
                tenInchButton.setText("10\"");

                twelveInchButton.setBackground(new java.awt.Color(171, 213, 255));
                twelveInchButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
                twelveInchButton.setText("12\"");

                sixInchButton.setBackground(new java.awt.Color(171, 213, 255));
                sixInchButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
                sixInchButton.setText("6\"");
                sixInchButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                sixInchButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(30, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sixInchButton)
                                        .addComponent(tenInchButton))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(twelveInchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(eightInchButton))
                                .addGap(23, 23, 23))
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(eightInchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sixInchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tenInchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(twelveInchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(24, Short.MAX_VALUE))
                );

                jPanel3.setBackground(new java.awt.Color(249, 172, 117));
                jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

                jLabel2.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
                jLabel2.setText("Number of layers:");

                oneLayerButton.setBackground(new java.awt.Color(171, 213, 255));
                oneLayerButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
                oneLayerButton.setText("1");
                oneLayerButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                oneLayerButtonActionPerformed(evt);
                        }
                });

                threeLayerButton.setBackground(new java.awt.Color(171, 213, 255));
                threeLayerButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
                threeLayerButton.setText("3");
                threeLayerButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                threeLayerButtonActionPerformed(evt);
                        }
                });

                twoLayerButton.setBackground(new java.awt.Color(171, 213, 255));
                twoLayerButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
                twoLayerButton.setText("2");
                twoLayerButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                twoLayerButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(oneLayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                                .addComponent(twoLayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(19, 19, 19))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(threeLayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60))
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(24, 24, 24)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(oneLayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(twoLayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(threeLayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(22, Short.MAX_VALUE))
                );

                jPanel4.setBackground(new java.awt.Color(249, 172, 117));
                jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

                jLabel3.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
                jLabel3.setText("Choose Type:");

                poundCakeButton.setBackground(new java.awt.Color(171, 213, 255));
                poundCakeButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
                poundCakeButton.setText("Pound Cake");
                poundCakeButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                poundCakeButtonActionPerformed(evt);
                        }
                });

                spongeCakeButton.setBackground(new java.awt.Color(171, 213, 255));
                spongeCakeButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
                spongeCakeButton.setText("Sponge Cake");
                spongeCakeButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                spongeCakeButtonActionPerformed(evt);
                        }
                });

                butterCakeButton.setBackground(new java.awt.Color(171, 213, 255));
                butterCakeButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
                butterCakeButton.setText("Butter Cake");
                butterCakeButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                butterCakeButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(poundCakeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(spongeCakeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(butterCakeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(22, Short.MAX_VALUE))
                );
                jPanel4Layout.setVerticalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(poundCakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spongeCakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(butterCakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(16, Short.MAX_VALUE))
                );

                jPanel6.setBackground(new java.awt.Color(249, 172, 117));
                jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

                jLabel5.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
                jLabel5.setText("Choose icing colour:");

                greenColorButton.setBackground(new java.awt.Color(0, 173, 48));
                greenColorButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
                greenColorButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                greenColorButtonActionPerformed(evt);
                        }
                });

                redColorButton.setBackground(new java.awt.Color(255, 46, 46));
                redColorButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
                redColorButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                redColorButtonActionPerformed(evt);
                        }
                });

                purpleColorButton.setBackground(new java.awt.Color(168, 128, 255));
                purpleColorButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
                purpleColorButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                purpleColorButtonActionPerformed(evt);
                        }
                });

                orangeColorButton.setBackground(new java.awt.Color(255, 149, 149));
                orangeColorButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
                orangeColorButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                orangeColorButtonActionPerformed(evt);
                        }
                });

                blueColorButton.setBackground(new java.awt.Color(3, 59, 255));
                blueColorButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
                blueColorButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                blueColorButtonActionPerformed(evt);
                        }
                });

                yellowColorButton.setBackground(new java.awt.Color(255, 240, 107));
                yellowColorButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
                yellowColorButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                yellowColorButtonActionPerformed(evt);
                        }
                });

                whiteColorButton.setBackground(new java.awt.Color(217, 217, 217));
                whiteColorButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
                whiteColorButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                whiteColorButtonActionPerformed(evt);
                        }
                });

                cyanColorButton.setBackground(new java.awt.Color(102, 200, 255));
                cyanColorButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
                cyanColorButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cyanColorButtonActionPerformed(evt);
                        }
                });

                pinkColorButton.setBackground(new java.awt.Color(253, 156, 255));
                pinkColorButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
                pinkColorButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                pinkColorButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
                jPanel6.setLayout(jPanel6Layout);
                jPanel6Layout.setHorizontalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap(56, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                                .addComponent(yellowColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cyanColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pinkColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                                .addComponent(orangeColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(blueColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(whiteColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(36, 36, 36))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(redColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(greenColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(purpleColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel5)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel6Layout.setVerticalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel5)
                                .addGap(8, 8, 8)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(greenColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(redColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(purpleColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(blueColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(orangeColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(whiteColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cyanColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(yellowColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pinkColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(19, Short.MAX_VALUE))
                );

                jPanel7.setBackground(new java.awt.Color(249, 172, 117));
                jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

                jLabel6.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
                jLabel6.setText("Message:");

                messageTextField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                messageTextFieldActionPerformed(evt);
                        }
                });

                okButton.setBackground(new java.awt.Color(204, 204, 255));
                okButton.setText("OK");

                javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
                jPanel7.setLayout(jPanel7Layout);
                jPanel7Layout.setHorizontalGroup(
                        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(messageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addComponent(okButton)))
                                .addContainerGap(27, Short.MAX_VALUE))
                );
                jPanel7Layout.setVerticalGroup(
                        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(messageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(okButton)
                                .addContainerGap(17, Short.MAX_VALUE))
                );

                jPanel8.setBackground(new java.awt.Color(249, 172, 117));
                jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

                jLabel4.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
                jLabel4.setText("Choose Filling:");

                chocolateFillingButton.setBackground(new java.awt.Color(171, 213, 255));
                chocolateFillingButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
                chocolateFillingButton.setText("Chocolate");
                chocolateFillingButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                chocolateFillingButtonActionPerformed(evt);
                        }
                });

                strawberryFillingButton.setBackground(new java.awt.Color(171, 213, 255));
                strawberryFillingButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
                strawberryFillingButton.setText("Strawberry");
                strawberryFillingButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                strawberryFillingButtonActionPerformed(evt);
                        }
                });

                vanillaFillingButton.setBackground(new java.awt.Color(171, 213, 255));
                vanillaFillingButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
                vanillaFillingButton.setText("Vanilla");
                vanillaFillingButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                vanillaFillingButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
                jPanel8.setLayout(jPanel8Layout);
                jPanel8Layout.setHorizontalGroup(
                        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(chocolateFillingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(strawberryFillingButton, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                        .addComponent(vanillaFillingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                jPanel8Layout.setVerticalGroup(
                        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(strawberryFillingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vanillaFillingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chocolateFillingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                );

                proceedButton.setBackground(new java.awt.Color(255, 153, 102));
                proceedButton.setFont(new java.awt.Font("The Bold Font", 0, 18)); // NOI18N
                proceedButton.setText("PROCEED");
                proceedButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                proceedButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                proceedButtonActionPerformed(evt);
                        }
                });

                btnProfile.setBackground(new java.awt.Color(255, 204, 204));
                btnProfile.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
                btnProfile.setText("PROFILE");
                btnProfile.setBorder(null);
                btnProfile.setBorderPainted(false);
                btnProfile.setContentAreaFilled(false);
                btnProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                btnProfile.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnProfileActionPerformed(evt);
                        }
                });

                btnCart.setBackground(new java.awt.Color(255, 204, 204));
                btnCart.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
                btnCart.setText("CART");
                btnCart.setBorder(null);
                btnCart.setBorderPainted(false);
                btnCart.setContentAreaFilled(false);
                btnCart.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCartActionPerformed(evt);
                        }
                });

                btnHome.setBackground(new java.awt.Color(255, 204, 204));
                btnHome.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
                btnHome.setText("HOME");
                btnHome.setBorder(null);
                btnHome.setBorderPainted(false);
                btnHome.setContentAreaFilled(false);
                btnHome.setDefaultCapable(false);
                btnHome.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnHomeActionPerformed(evt);
                        }
                });

                btnItems.setBackground(new java.awt.Color(255, 204, 204));
                btnItems.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
                btnItems.setText("ITEMS");
                btnItems.setBorder(null);
                btnItems.setBorderPainted(false);
                btnItems.setContentAreaFilled(false);
                btnItems.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnItemsActionPerformed(evt);
                        }
                });

                btnContactUs.setBackground(new java.awt.Color(255, 204, 204));
                btnContactUs.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
                btnContactUs.setText("DETAILS");
                btnContactUs.setBorder(null);
                btnContactUs.setContentAreaFilled(false);
                btnContactUs.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnContactUsActionPerformed(evt);
                        }
                });

                btnAboutUs.setBackground(new java.awt.Color(255, 204, 204));
                btnAboutUs.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
                btnAboutUs.setText("ABOUT US");
                btnAboutUs.setBorder(null);
                btnAboutUs.setContentAreaFilled(false);
                btnAboutUs.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAboutUsActionPerformed(evt);
                        }
                });

                jPanel5.setBackground(new java.awt.Color(249, 172, 117));
                jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

                jLabel7.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
                jLabel7.setText("Size:");

                jLabel8.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
                jLabel8.setText("Layers:");

                jLabel9.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
                jLabel9.setText("Cake Type:");

                jLabel10.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
                jLabel10.setText("Icing Colour:");

                jLabel11.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
                jLabel11.setText("Filling");

                jLabel12.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
                jLabel12.setText("Message:");

                SizeField.setEditable(false);
                SizeField.setBackground(new java.awt.Color(255, 255, 255));
                SizeField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                SizeFieldActionPerformed(evt);
                        }
                });

                cakeTypeField.setEditable(false);
                cakeTypeField.setBackground(new java.awt.Color(255, 255, 255));
                cakeTypeField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cakeTypeFieldActionPerformed(evt);
                        }
                });

                icingColorField.setEditable(false);
                icingColorField.setBackground(new java.awt.Color(255, 255, 255));
                icingColorField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                icingColorFieldActionPerformed(evt);
                        }
                });

                messageField.setEditable(false);
                messageField.setBackground(new java.awt.Color(255, 255, 255));
                messageField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                messageFieldActionPerformed(evt);
                        }
                });

                layersField.setEditable(false);
                layersField.setBackground(new java.awt.Color(255, 255, 255));
                layersField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                layersFieldActionPerformed(evt);
                        }
                });

                fillingField.setEditable(false);
                fillingField.setBackground(new java.awt.Color(255, 255, 255));
                fillingField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                fillingFieldActionPerformed(evt);
                        }
                });

                btnHome1.setBackground(new java.awt.Color(255, 204, 204));
                btnHome1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
                btnHome1.setText("FINAL PRODUCT");
                btnHome1.setBorder(null);
                btnHome1.setBorderPainted(false);
                btnHome1.setContentAreaFilled(false);
                btnHome1.setDefaultCapable(false);
                btnHome1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnHome1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap(77, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(20, 20, 20)
                                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(SizeField)
                                                                        .addComponent(layersField)
                                                                        .addComponent(cakeTypeField)
                                                                        .addComponent(icingColorField)
                                                                        .addComponent(fillingField)
                                                                        .addComponent(messageField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(77, 77, 77))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                .addComponent(btnHome1)
                                                .addGap(100, 100, 100))))
                );
                jPanel5Layout.setVerticalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addContainerGap(30, Short.MAX_VALUE)
                                .addComponent(btnHome1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(SizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(layersField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(cakeTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(icingColorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(fillingField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(messageField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37))
                );

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(btnProfile)
                                .addGap(51, 51, 51)
                                .addComponent(btnCart)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHome)
                                .addGap(38, 38, 38)
                                .addComponent(btnItems)
                                .addGap(45, 45, 45)
                                .addComponent(btnContactUs)
                                .addGap(37, 37, 37)
                                .addComponent(btnAboutUs)
                                .addGap(65, 65, 65))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(31, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(57, 57, 57)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(6, 6, 6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(proceedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(154, 154, 154))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(53, 53, 53))))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnProfile)
                                        .addComponent(btnCart)
                                        .addComponent(btnHome)
                                        .addComponent(btnItems)
                                        .addComponent(btnContactUs)
                                        .addComponent(btnAboutUs))
                                .addGap(26, 26, 26)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(42, 42, 42)
                                                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 30, Short.MAX_VALUE)
                                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(36, 36, 36)
                                                .addComponent(proceedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(56, 56, 56))))
                );

                getContentPane().add(jPanel1);
                jPanel1.setBounds(0, 0, 1200, 660);

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void proceedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proceedButtonActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
    
        ProfileView JFI = new ProfileView();
        JFI.fillCustomersData(rModel);

        JFI.show();
        //        dispose();

    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartActionPerformed
        // TODO add your handling code here:
        CartView CV = new CartView();
        CV.show();
        dispose();
    }//GEN-LAST:event_btnCartActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        DashboardView DaB = new DashboardView();
        DaB.show();
        dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemsActionPerformed
        // TODO add your handling code here:
        ItemsView JFI = new ItemsView();
        JFI.show();
        dispose();
    }//GEN-LAST:event_btnItemsActionPerformed

    private void btnContactUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactUsActionPerformed
        // TODO add your handling code here:
        ContactUs CoV = new ContactUs();
        CoV.show();
        dispose();

    }//GEN-LAST:event_btnContactUsActionPerformed

    private void btnAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutUsActionPerformed
        // TODO add your handling code here:
        AboutUs AV = new AboutUs();
        AV.show();
        dispose();
        //
    }//GEN-LAST:event_btnAboutUsActionPerformed

    private void sixInchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixInchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sixInchButtonActionPerformed

    private void oneLayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneLayerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneLayerButtonActionPerformed

    private void threeLayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeLayerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_threeLayerButtonActionPerformed

    private void twoLayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoLayerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twoLayerButtonActionPerformed

    private void poundCakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poundCakeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poundCakeButtonActionPerformed

    private void spongeCakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spongeCakeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spongeCakeButtonActionPerformed

    private void butterCakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butterCakeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butterCakeButtonActionPerformed

    private void chocolateFillingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chocolateFillingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chocolateFillingButtonActionPerformed

    private void strawberryFillingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strawberryFillingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strawberryFillingButtonActionPerformed

    private void vanillaFillingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vanillaFillingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vanillaFillingButtonActionPerformed

    private void greenColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenColorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_greenColorButtonActionPerformed

    private void redColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redColorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redColorButtonActionPerformed

    private void purpleColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purpleColorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purpleColorButtonActionPerformed

    private void orangeColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orangeColorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orangeColorButtonActionPerformed

    private void blueColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueColorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueColorButtonActionPerformed

    private void yellowColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yellowColorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yellowColorButtonActionPerformed

    private void whiteColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiteColorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_whiteColorButtonActionPerformed

    private void cyanColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cyanColorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cyanColorButtonActionPerformed

    private void pinkColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinkColorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinkColorButtonActionPerformed

    private void eightInchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightInchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eightInchButtonActionPerformed

    private void messageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageTextFieldActionPerformed

    private void SizeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SizeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SizeFieldActionPerformed

    private void cakeTypeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cakeTypeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cakeTypeFieldActionPerformed

    private void icingColorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icingColorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_icingColorFieldActionPerformed

    private void messageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageFieldActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void layersFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_layersFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_layersFieldActionPerformed

    private void fillingFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillingFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fillingFieldActionPerformed

    private void btnHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomizeCakeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomizeCakeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomizeCakeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomizeCakeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomizeCakeView().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTextField SizeField;
        private javax.swing.JButton blueColorButton;
        private javax.swing.JButton btnAboutUs;
        private javax.swing.JButton btnCart;
        private javax.swing.JButton btnContactUs;
        private javax.swing.JButton btnHome;
        private javax.swing.JButton btnHome1;
        private javax.swing.JButton btnItems;
        private javax.swing.JButton btnProfile;
        private javax.swing.JButton butterCakeButton;
        private javax.swing.JTextField cakeTypeField;
        private javax.swing.JButton chocolateFillingButton;
        private javax.swing.JButton cyanColorButton;
        private javax.swing.JButton eightInchButton;
        private javax.swing.JTextField fillingField;
        private javax.swing.JButton greenColorButton;
        private javax.swing.JTextField icingColorField;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanel6;
        private javax.swing.JPanel jPanel7;
        private javax.swing.JPanel jPanel8;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JTextField jTextField6;
        private javax.swing.JTextField layersField;
        private javax.swing.JTextField messageField;
        private javax.swing.JTextField messageTextField;
        private javax.swing.JButton okButton;
        private javax.swing.JButton oneLayerButton;
        private javax.swing.JButton orangeColorButton;
        private javax.swing.JButton pinkColorButton;
        private javax.swing.JButton poundCakeButton;
        private javax.swing.JButton proceedButton;
        private javax.swing.JButton purpleColorButton;
        private javax.swing.JButton redColorButton;
        private javax.swing.JButton sixInchButton;
        private javax.swing.JButton spongeCakeButton;
        private javax.swing.JButton strawberryFillingButton;
        private javax.swing.JButton tenInchButton;
        private javax.swing.JButton threeLayerButton;
        private javax.swing.JButton twelveInchButton;
        private javax.swing.JButton twoLayerButton;
        private javax.swing.JButton vanillaFillingButton;
        private javax.swing.JButton whiteColorButton;
        private javax.swing.JButton yellowColorButton;
        // End of variables declaration//GEN-END:variables
}
