package view;


import java.sql.*;
import javax.swing.JOptionPane;
import java.awt.event.ActionListener;

import model.*;
import controller.*;



public class RegistrationView extends javax.swing.JFrame {
    RegistrationModel model;
    Connection conn;
    /**
     * Creates new form RegistrationPage
     */
    public RegistrationView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showpass = new javax.swing.JCheckBox();
        repeatPasswordField = new javax.swing.JPasswordField();
        passwordField = new javax.swing.JPasswordField();
        emailField = new javax.swing.JTextField();
        fnameField = new javax.swing.JTextField();
        lnameField = new javax.swing.JTextField();
        dayField = new javax.swing.JComboBox<>();
        monthField = new javax.swing.JComboBox<>();
        yearField = new javax.swing.JComboBox<>();
        unameField1 = new javax.swing.JTextField();
        sec = new javax.swing.JTextField();
        aans = new javax.swing.JTextField();
        RegisterButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1040, 681));
        getContentPane().setLayout(null);

        showpass.setBackground(new java.awt.Color(231, 228, 213));
        showpass.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        showpass.setForeground(new java.awt.Color(0, 0, 0));
        showpass.setText("Show Password");
        showpass.setBorder(null);
        showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassActionPerformed(evt);
            }
        });
        getContentPane().add(showpass);
        showpass.setBounds(800, 370, 119, 19);

        repeatPasswordField.setBackground(new java.awt.Color(217, 217, 217));
        repeatPasswordField.setForeground(new java.awt.Color(102, 102, 102));
        repeatPasswordField.setBorder(null);
        getContentPane().add(repeatPasswordField);
        repeatPasswordField.setBounds(750, 338, 150, 20);

        passwordField.setBackground(new java.awt.Color(217, 217, 217));
        passwordField.setForeground(new java.awt.Color(102, 102, 102));
        passwordField.setBorder(null);
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(passwordField);
        passwordField.setBounds(580, 338, 150, 20);

        emailField.setBackground(new java.awt.Color(217, 217, 217));
        emailField.setForeground(new java.awt.Color(102, 102, 102));
        emailField.setBorder(null);
        getContentPane().add(emailField);
        emailField.setBounds(200, 340, 300, 20);

        fnameField.setBackground(new java.awt.Color(217, 217, 217));
        fnameField.setForeground(new java.awt.Color(102, 102, 102));
        fnameField.setBorder(null);
        fnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(fnameField);
        fnameField.setBounds(200, 260, 130, 20);

        lnameField.setBackground(new java.awt.Color(217, 217, 217));
        lnameField.setForeground(new java.awt.Color(102, 102, 102));
        lnameField.setBorder(null);
        lnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(lnameField);
        lnameField.setBounds(370, 260, 130, 20);

        dayField.setBackground(new java.awt.Color(217, 217, 217));
        dayField.setForeground(new java.awt.Color(102, 102, 102));
        dayField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "day", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dayField.setBorder(null);
        dayField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayFieldActionPerformed(evt);
            }
        });
        getContentPane().add(dayField);
        dayField.setBounds(200, 420, 70, 30);

        monthField.setBackground(new java.awt.Color(217, 217, 217));
        monthField.setForeground(new java.awt.Color(102, 102, 102));
        monthField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "month", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        monthField.setBorder(null);
        getContentPane().add(monthField);
        monthField.setBounds(280, 420, 80, 30);

        yearField.setBackground(new java.awt.Color(217, 217, 217));
        yearField.setForeground(new java.awt.Color(102, 102, 102));
        yearField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "year", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", " ", " " }));
        yearField.setBorder(null);
        getContentPane().add(yearField);
        yearField.setBounds(370, 420, 70, 30);

        unameField1.setBackground(new java.awt.Color(217, 217, 217));
        unameField1.setForeground(new java.awt.Color(102, 102, 102));
        unameField1.setBorder(null);
        unameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameField1ActionPerformed(evt);
            }
        });
        getContentPane().add(unameField1);
        unameField1.setBounds(590, 260, 250, 20);

        sec.setBackground(new java.awt.Color(217, 217, 217));
        sec.setForeground(new java.awt.Color(102, 102, 102));
        sec.setBorder(null);
        sec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secActionPerformed(evt);
            }
        });
        getContentPane().add(sec);
        sec.setBounds(590, 400, 260, 20);

        aans.setBackground(new java.awt.Color(217, 217, 217));
        aans.setForeground(new java.awt.Color(102, 102, 102));
        aans.setBorder(null);
        aans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aansActionPerformed(evt);
            }
        });
        getContentPane().add(aans);
        aans.setBounds(590, 470, 260, 20);

        RegisterButton.setBackground(new java.awt.Color(239, 215, 154));
        RegisterButton.setFont(new java.awt.Font("The Bold Font", 0, 18)); // NOI18N
        RegisterButton.setForeground(new java.awt.Color(0, 0, 0));
        RegisterButton.setText("Register");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RegisterButton);
        RegisterButton.setBounds(470, 520, 130, 30);

        jLabel9.setForeground(javax.swing.UIManager.getDefaults().getColor("nb.diff.sidebar.deleted.color"));
        jLabel9.setText("Already have an account? ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(440, 560, 150, 38);

        LoginButton.setBackground(new java.awt.Color(231, 228, 213));
        LoginButton.setForeground(new java.awt.Color(84, 42, 42));
        LoginButton.setText("Login");
        LoginButton.setBorder(null);
        LoginButton.setBorderPainted(false);
        LoginButton.setContentAreaFilled(false);
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LoginButton);
        LoginButton.setBounds(570, 570, 70, 16);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Realregistration.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1040, 680);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameFieldActionPerformed

    private void secActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secActionPerformed
    
    public RegistrationModel setNewUser(){
        String DOB=yearField.getSelectedItem().toString()+"-"+convertDateToNum(monthField.getSelectedItem().toString())+"-"+dayField.getSelectedItem().toString();
        model = new RegistrationModel(fnameField.getText(), lnameField.getText(), emailField.getText(), DOB, unameField1.getText(), passwordField.getText(), repeatPasswordField.getText(),sec.getText(), aans.getText());
        return model;
    }
    
    public static String convertDateToNum(String date){
        /*
        * Takes month names in String
        * @return the corresponding numeric value.
        */
        switch (date){
            case "Jan":
                return "01";
            case "Feb":
                return "02";
            case "Mar":
                return "03";
            case "Apr":
                return "04";
            case "May":
                return "05";
            case "Jun":
                return "06";
            case "Jul":
                return "07";
            case "Aug":
                return "08";
            case "Sep":
                return "09";
            case "Oct":
                return "10";
            case "Nov":
                return "11";
            case "Dec":
                return "12";
            default:
                return "invalid";
        }
    }
    
    public void displayPlainMessage(String message, String title){
        JOptionPane.showMessageDialog(this, message, title, JOptionPane.PLAIN_MESSAGE);
    }
    
    public void displayErrorMessage(String message){
        JOptionPane.showMessageDialog(rootPane, message, "error", JOptionPane.ERROR_MESSAGE);
    }
    
    
    public void addRegistrationListner(ActionListener log){
        RegisterButton.addActionListener(log);
    }
    
    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        new RegistrationController(this);
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void dayFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayFieldActionPerformed
    }//GEN-LAST:event_dayFieldActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        LoginView LV = new LoginView();
        LV.show();
        dispose();
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void unameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameField1ActionPerformed

    }//GEN-LAST:event_unameField1ActionPerformed

    private void aansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aansActionPerformed

    private void lnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameFieldActionPerformed

    private void showpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassActionPerformed
        // TODO add your handling code here:
        if(showpass.isSelected()){
            passwordField.setEchoChar((char)0);
            repeatPasswordField.setEchoChar((char)0);
        }
        else{
            passwordField.setEchoChar('•');
            repeatPasswordField.setEchoChar('•');
        }
    }//GEN-LAST:event_showpassActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationView().setVisible(true);
            }
        });
    }
    
    //<editor-fold defaultstate="collapsed" desc=" javax.swing declarations">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JButton RegisterButton;
    public javax.swing.JTextField aans;
    public javax.swing.JComboBox<String> dayField;
    public javax.swing.JTextField emailField;
    public javax.swing.JTextField fnameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField lnameField;
    public javax.swing.JComboBox<String> monthField;
    public javax.swing.JPasswordField passwordField;
    public javax.swing.JPasswordField repeatPasswordField;
    public javax.swing.JTextField sec;
    private javax.swing.JCheckBox showpass;
    public javax.swing.JTextField unameField1;
    public javax.swing.JComboBox<String> yearField;
    // End of variables declaration//GEN-END:variables
}
//</editor-fold>